"""Interactive first-run wizard.

Walks the user through picking providers, gathering credentials, generating a
`REPLAN_TOKEN`, creating the Anthropic environment + agent, and (on macOS)
compiling `macos/reminders_fetch`. Writes everything to `.env`.

Re-runnable: existing values in `.env` are shown as defaults; pressing Enter
keeps them. Nothing is overwritten without a prompt.

Run:
    python install.py

No arguments. Quit at any prompt with Ctrl-C — no state is persisted until
the final "Write .env?" confirmation, so aborting is safe.
"""
from __future__ import annotations

import os
import secrets
import subprocess
import sys
from getpass import getpass
from pathlib import Path
from typing import Optional

from paths import env_path

PROJECT_DIR = Path(__file__).resolve().parent
ENV_PATH = env_path()  # repo dir in dev; ~/Library/Application Support/... in a frozen app

# All keys install.py knows about, in the order we want them written. Keys
# absent from the user's picks are still preserved in .env if present.
_KEYS = [
    "ANTHROPIC_API_KEY", "REPLAN_TOKEN", "TIMEZONE",
    "DEFAULT_REQUIRE_APPROVAL",
    "ENVIRONMENT_ID", "AGENT_ID",
    # Calendar — pick one backend
    "ICLOUD_USER", "ICLOUD_APP_PASSWORD", "WRITE_CALENDAR_NAME",
    "GOOGLE_CALENDAR_CREDENTIALS",
    "MICROSOFT_CLIENT_ID", "MICROSOFT_TENANT", "ENABLE_OUTLOOK_CALENDAR",
    "CALDAV_URL", "CALDAV_USER", "CALDAV_PASSWORD",
    # Task sources — any combination
    "CANVAS_TOKEN", "CANVAS_BASE_URL",
    "TODOIST_TOKEN",
    "ENABLE_GMAIL_SCAN", "GMAIL_LABEL_FILTER", "GMAIL_MAX_MESSAGES",
    "ENABLE_GOOGLE_TASKS",
    "ENABLE_OUTLOOK_MAIL_SCAN", "OUTLOOK_MAIL_FOLDER",
    "OUTLOOK_CATEGORY_FILTER", "OUTLOOK_MAX_MESSAGES",
    "ENABLE_MICROSOFT_TODO",
    # Notifier — pick one
    "USER_PHONE",
    "PUSHOVER_USER_KEY", "PUSHOVER_APP_TOKEN", "PUSHOVER_DEVICE",
    "SLACK_WEBHOOK_URL", "SLACK_USERNAME", "SLACK_ICON_EMOJI",
    "SMTP_HOST", "SMTP_PORT", "SMTP_USERNAME", "SMTP_PASSWORD",
    "SMTP_FROM", "SMTP_TO", "SMTP_USE_TLS", "SMTP_USE_SSL",
    "NTFY_TOPIC",
]


# ---------- terminal I/O ----------

_BOLD = "\033[1m"
_DIM = "\033[2m"
_GREEN = "\033[32m"
_YELLOW = "\033[33m"
_RED = "\033[31m"
_RESET = "\033[0m"


def _say(msg: str = "") -> None:
    print(msg)


def _header(title: str) -> None:
    _say()
    _say(f"{_BOLD}── {title} ──{_RESET}")


def _dim(msg: str) -> None:
    _say(f"{_DIM}{msg}{_RESET}")


def _ok(msg: str) -> None:
    _say(f"{_GREEN}✓ {msg}{_RESET}")


def _warn(msg: str) -> None:
    _say(f"{_YELLOW}! {msg}{_RESET}")


def _err(msg: str) -> None:
    _say(f"{_RED}✗ {msg}{_RESET}")


def _prompt(label: str, *, default: Optional[str] = None,
            secret: bool = False, required: bool = True) -> str:
    default_shown = f" [{default}]" if default else ""
    while True:
        suffix = ": "
        prompt = f"{label}{default_shown}{suffix}"
        raw = getpass(prompt) if secret else input(prompt)
        value = raw.strip() or (default or "")
        if value or not required:
            return value
        _warn("Value required.")


def _yes_no(label: str, *, default: bool = True) -> bool:
    hint = "[Y/n]" if default else "[y/N]"
    while True:
        raw = input(f"{label} {hint}: ").strip().lower()
        if not raw:
            return default
        if raw in ("y", "yes"):
            return True
        if raw in ("n", "no"):
            return False
        _warn("Please answer y or n.")


def _choice(label: str, options: list[tuple[str, str]], *,
            default_index: int = 0) -> str:
    """options: list of (key, description). Returns the chosen key."""
    _say(label)
    for i, (_, desc) in enumerate(options):
        marker = "→" if i == default_index else " "
        _say(f"  {marker} {i + 1}. {desc}")
    while True:
        raw = input(f"Pick [1-{len(options)}, Enter = {default_index + 1}]: ").strip()
        if not raw:
            return options[default_index][0]
        try:
            idx = int(raw) - 1
        except ValueError:
            _warn("Enter a number.")
            continue
        if 0 <= idx < len(options):
            return options[idx][0]
        _warn(f"Pick 1-{len(options)}.")


# ---------- .env read/write ----------

def _read_env() -> dict[str, str]:
    """Parse .env into a dict. Ignores comments and unknown keys."""
    if not ENV_PATH.exists():
        return {}
    out: dict[str, str] = {}
    for line in ENV_PATH.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip().strip("'").strip('"')
    return out


def _write_env(env: dict[str, str]) -> None:
    """Write .env with our known keys (in order) plus any other keys
    (preserved, appended at the end). Quote values that contain spaces."""
    lines: list[str] = [
        "# Generated by install.py. Edit by hand if you like; re-running",
        "# install.py will keep unchanged values as defaults.",
        "",
    ]
    for k in _KEYS:
        v = env.get(k)
        if v is None or v == "":
            lines.append(f"# {k}=")
            continue
        lines.append(f"{k}={_quote(v)}")
    extras = [k for k in env if k not in _KEYS]
    if extras:
        lines.append("")
        lines.append("# Keys install.py doesn't manage (preserved as-is):")
        for k in extras:
            v = env[k]
            if v:
                lines.append(f"{k}={_quote(v)}")
    ENV_PATH.write_text("\n".join(lines) + "\n")


def _quote(v: str) -> str:
    return v if not any(c.isspace() for c in v) else f'"{v}"'


# ---------- wizard steps ----------

def _welcome() -> None:
    _say(f"{_BOLD}schedule-agent install{_RESET}")
    _say("This wizard will gather credentials, write .env, create your")
    _say("Anthropic agent, and (on macOS) compile the Reminders helper.")
    _say("You can re-run it any time. Ctrl-C aborts without writing anything.")


def _core(env: dict[str, str]) -> None:
    _header("Core settings")
    env["ANTHROPIC_API_KEY"] = _prompt(
        "Anthropic API key (get one at console.anthropic.com/settings/keys)",
        default=env.get("ANTHROPIC_API_KEY") or None, secret=True,
    )
    tok = env.get("REPLAN_TOKEN")
    if not tok:
        tok = secrets.token_urlsafe(32)
        _dim(f"Generated REPLAN_TOKEN (used for hub auth). Save your hub URL: "
             f"/hub?key={tok[:8]}…")
    env["REPLAN_TOKEN"] = tok
    env["TIMEZONE"] = _prompt(
        "Your timezone (any IANA zone, e.g. America/New_York)",
        default=env.get("TIMEZONE") or "America/New_York",
    )


def _calendar(env: dict[str, str]) -> str:
    _header("Calendar provider")
    _dim("The solver writes Study Blocks into this calendar.")
    choice = _choice("Which calendar backend?", [
        ("icloud", "iCloud CalDAV (Apple Calendar)"),
        ("skip", "Skip — I'll configure this later in schedule_config.py"),
    ])
    if choice == "icloud":
        _dim("Your ICLOUD_USER is the primary Apple ID email (NOT a @icloud.com")
        _dim("alias if those differ). ICLOUD_APP_PASSWORD is an app-specific")
        _dim("password from appleid.apple.com — NOT your regular Apple password.")
        env["ICLOUD_USER"] = _prompt("Apple ID email",
                                     default=env.get("ICLOUD_USER") or None)
        env["ICLOUD_APP_PASSWORD"] = _prompt(
            "App-specific password (xxxx-xxxx-xxxx-xxxx)",
            default=env.get("ICLOUD_APP_PASSWORD") or None, secret=True,
        )
        env["WRITE_CALENDAR_NAME"] = _prompt(
            "Calendar name where solver writes Study Blocks",
            default=env.get("WRITE_CALENDAR_NAME") or "Study Blocks",
        )
        _dim("Create that calendar in Calendar.app first if it doesn't exist.")
    return choice


def _task_source(env: dict[str, str]) -> str:
    _header("Task source")
    _dim("Where upstream work items come from (LMS, issue tracker, …).")
    choice = _choice("Which task source?", [
        ("canvas", "Canvas LMS"),
        ("skip", "None / manual only"),
    ])
    if choice == "canvas":
        env["CANVAS_BASE_URL"] = _prompt(
            "Canvas API base URL",
            default=env.get("CANVAS_BASE_URL")
            or "https://psu.instructure.com/api/v1",
        )
        _dim("Get a personal access token at <canvas>/profile/settings → New Access Token.")
        env["CANVAS_TOKEN"] = _prompt(
            "Canvas access token",
            default=env.get("CANVAS_TOKEN") or None, secret=True,
        )
    return choice


def _todo_source(env: dict[str, str]) -> str:
    _header("Todo-app cross-reference (optional)")
    _dim("Closing a matching reminder/todo auto-marks the task done.")
    options = [("apple_reminders", "Apple Reminders (macOS only)"),
               ("none", "None")]
    default_idx = 0 if sys.platform == "darwin" else 1
    return _choice("Todo source?", options, default_index=default_idx)


def _notifier(env: dict[str, str]) -> str:
    _header("Notifier")
    _dim("How the agent reaches you with summaries and updates.")
    options = [
        ("imessage", "iMessage (macOS only; self-send shows in Messages badge, "
                     "no iOS push — see README §M2)"),
        ("ntfy", "ntfy.sh (cross-platform, real push, free)"),
    ]
    default_idx = 0 if sys.platform == "darwin" else 1
    choice = _choice("Which notifier?", options, default_index=default_idx)
    if choice == "imessage":
        env["USER_PHONE"] = _prompt(
            "Your phone number in E.164 format (e.g. +15551234567)",
            default=env.get("USER_PHONE") or None,
        )
    elif choice == "ntfy":
        topic = env.get("NTFY_TOPIC")
        if not topic:
            topic = f"schedule-agent-{secrets.token_urlsafe(16)}"
            _dim("Generated a random ntfy topic. Treat it as a secret — anyone")
            _dim("who knows it can read AND publish your notifications.")
        env["NTFY_TOPIC"] = _prompt(
            "ntfy topic (anything hard to guess)", default=topic,
        )
        _dim(f"Subscribe the ntfy mobile app to this topic to receive pushes.")
    return choice


def _write_schedule_config_hint(picks: dict[str, str]) -> None:
    _header("Next: schedule_config.py")
    _dim("The wizard writes credentials to .env, but schedule_config.py is what")
    _dim("decides which provider classes to instantiate. Review it against the")
    _dim("choices you made above:")
    _say()
    if picks["calendar"] == "skip":
        _warn("You skipped the calendar step — orchestrator won't start until you")
        _warn("either wire a CalendarProvider in schedule_config.py or set one of")
        _warn("the calendar env vars manually.")
    if picks["task_source"] == "skip":
        _say("  • TASK_SOURCES: set to an empty list or comment out CanvasTaskSource.")
    if picks["todo_source"] == "none":
        _say("  • TODO_SOURCE: set to None.")
    if picks["notifier"] == "ntfy":
        _say("  • NOTIFIER: swap IMessageNotifier for the NtfyNotifier block "
             "(commented example already present).")


def _run_setup_py() -> bool:
    """Invoke setup.py as a subprocess so it picks up the fresh .env we just
    wrote. Returns True on success."""
    _header("Create Anthropic environment + agent")
    _dim("Running setup.py (creates a new env_ and agent_ id and writes them")
    _dim("back into .env).")
    try:
        r = subprocess.run([sys.executable, "setup.py"],
                           cwd=PROJECT_DIR, check=False)
    except Exception as ex:
        _err(f"Couldn't run setup.py: {type(ex).__name__}: {ex}")
        return False
    if r.returncode != 0:
        _err(f"setup.py exited {r.returncode}. Fix the error above and re-run.")
        return False
    _ok("Anthropic agent created.")
    return True


def _maybe_compile_swift(picks: dict[str, str]) -> None:
    if picks.get("todo_source") != "apple_reminders":
        return
    if sys.platform != "darwin":
        _warn("Apple Reminders was picked but this doesn't look like macOS. Skipping swiftc.")
        return
    binary = PROJECT_DIR / "macos" / "reminders_fetch"
    if binary.exists():
        _ok(f"{binary.name} already compiled.")
        return
    _header("Compile macos/reminders_fetch")
    if not _yes_no("Compile the Swift Reminders helper now?", default=True):
        _warn("Skipped. Run `cd macos && swiftc -O -o reminders_fetch "
              "reminders_fetch.swift` before first use.")
        return
    src = PROJECT_DIR / "macos" / "reminders_fetch.swift"
    try:
        r = subprocess.run(["swiftc", "-O", "-o", str(binary), str(src)],
                           check=False)
    except FileNotFoundError:
        _err("swiftc not found. Install Xcode command line tools: xcode-select --install")
        return
    if r.returncode == 0:
        _ok(f"Built {binary}.")
        _dim("First run will prompt for Reminders TCC permission.")
    else:
        _err(f"swiftc exited {r.returncode}.")


def _run_health_checks() -> None:
    _header("Provider health check")
    # Reload env vars now that .env is populated.
    for line in ENV_PATH.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        os.environ.setdefault(k.strip(), v.strip().strip("'").strip('"'))
    try:
        import schedule_config as _sc
    except Exception as ex:
        _err(f"schedule_config.py didn't import: {type(ex).__name__}: {ex}")
        _warn("Fix the error and re-run `python -c 'import schedule_config'` to verify.")
        return
    try:
        health = _sc.providers_health()
    except Exception as ex:
        _err(f"providers_health() raised: {type(ex).__name__}: {ex}")
        return
    for key, val in health.items():
        if isinstance(val, list):
            for item in val:
                _report_health(f"{key}[{item.get('source','?')}]", item)
        elif isinstance(val, dict):
            _report_health(key, val)
        else:
            _say(f"  {key}: {val}")


def _report_health(label: str, info: dict) -> None:
    if info.get("error"):
        _err(f"{label}: {info['error']}")
    else:
        detail_keys = [k for k in info if k not in ("error", "provider", "source", "channel")]
        detail = ", ".join(f"{k}={info[k]}" for k in detail_keys[:4])
        _ok(f"{label}: {detail or 'ok'}")


def _final_summary() -> None:
    _header("All set")
    _say("Start the orchestrator:")
    _say(f"  {_BOLD}python orchestrator.py{_RESET}")
    _say("Then open the hub:")
    _say("  http://127.0.0.1:8787/hub?key=<REPLAN_TOKEN from .env>")
    if sys.platform == "darwin":
        _say()
        _say("For lifetime service on macOS: see macos/README.md for the")
        _say("LaunchAgent plist template and `launchctl load` command.")


def main() -> int:
    env = _read_env()
    picks: dict[str, str] = {}
    try:
        _welcome()
        _core(env)
        picks["calendar"] = _calendar(env)
        picks["task_source"] = _task_source(env)
        picks["todo_source"] = _todo_source(env)
        picks["notifier"] = _notifier(env)
    except (KeyboardInterrupt, EOFError):
        _say()
        _warn("Aborted. No changes written.")
        return 130

    _header("Review")
    for k in _KEYS:
        if k in env and env[k]:
            shown = (env[k][:3] + "…" + env[k][-3:]) if k.endswith(("TOKEN", "PASSWORD", "API_KEY")) and len(env[k]) > 8 else env[k]
            _say(f"  {k} = {shown}")
    if not _yes_no(f"\nWrite these to {ENV_PATH}?", default=True):
        _warn("Aborted before write.")
        return 0

    _write_env(env)
    _ok(f"Wrote {ENV_PATH}.")

    _write_schedule_config_hint(picks)

    # Create Anthropic agent (needs the .env we just wrote).
    if _yes_no("\nRun setup.py now to create your Anthropic environment + agent?",
               default=True):
        if not _run_setup_py():
            return 1

    _maybe_compile_swift(picks)
    _run_health_checks()
    _final_summary()
    return 0


if __name__ == "__main__":
    sys.exit(main())
